language: python

python:
  - "3.4"
  
sudo: true

before_install:
 - sudo apt-get update
 - sudo apt-get install python-opencv
 - sudo apt-get install -qq python-numpy python-scipy
 - sudo dpkg -L python-opencv

install:
  - "pip install -r requirements.txt"

script:
  - python src/test/main_test.py
